#!/bin/sh
#
# Prints color-test blocks

i=0
for bgv in 4 10
do
	for bg in 0 1 2 3 4 5 6 7
	do
		printf ' \033[3%d;%d%dm  %2d   \033[m' \
			$(($bg == 7 || $bg == 15 ? 0 : 7)) "$bgv" "$bg" "$i"
		i=$((i + 1))
	done
	printf '\n'
done
printf '\n'

str='  gYw  '
for fg in 0 1 2 3 4 5 6 7
do
	for wgt in 0 1
	do
		printf ' \033[%d;3%dm%s\033[m' "$wgt" "$fg" "$str"
		for bg in 0 1 2 3 4 5 6 7
		do
			printf ' \033[%d;3%d;4%dm%s\033[m' \
				"$wgt" "$fg" "$bg" "$str"
		done
		printf '\n'
	done
done
